// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    PanelGroup: typeof import('./src/components/PanelGroup.vue')['default']
    Pomo: typeof import('./src/components/Pomo.vue')['default']
    PomoDialog: typeof import('./src/components/pomos/PomoDialog.vue')['default']
    PomoHeader: typeof import('./src/components/pomos/PomoHeader.vue')['default']
    PomoHistory: typeof import('./src/components/dataStatistics/PomoHistory.vue')['default']
    PomoList: typeof import('./src/components/pomos/PomoList.vue')['default']
    PomoStatistics: typeof import('./src/components/dataStatistics/PomoStatistics.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatChart: typeof import('./src/components/dataStatistics/StatChart.vue')['default']
    Todo: typeof import('./src/components/Todo.vue')['default']
    TodoFooter: typeof import('./src/components/todos/TodoFooter.vue')['default']
    TodoHeader: typeof import('./src/components/todos/TodoHeader.vue')['default']
    TodoItem: typeof import('./src/components/todos/TodoItem.vue')['default']
    TodoList: typeof import('./src/components/todos/TodoList.vue')['default']
  }
}

export {}
